### ISSUE TITLE
[Bug] Can not begin to use issue

### ISSUE THREAD

**Issue by Kristinita** [eerohele/exalt#3]
### 1. Summary

Exalt not worked for me.

### 2. Expected behavior

Successful validate and format XML files.

### 3. Actual behavior

1. I don't see [**Exalt commands**](https://github.com/eerohele/exalt/blob/master/Default.sublime-commands) in command palette.

![Exalt in command palette](http://i.imgur.com/uSoAIr9.png)

2. If I run `exalt_validate` and `exalt_format_document` commands, nothing occurs.

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install Exalt via Package Control → I restart Sublime Text → I open some `.xml` files, for example, [**opensearch.xml**](https://github.com/Kristinita/Kristinita.github.io/blob/master/opensearch.xml) or [**with_fries.xml**](https://github.com/Kristinita/Kristinita.github.io/blob/master/bower-components/jQuery/test/data/with_fries.xml) or [**SashaSublime.tmTheme**](https://github.com/Kristinita/SashaSublime/blob/master/SashaSublime.tmTheme). I deliberately made mistakes in these files, that to see, how Exalt to work.

<kbd>Ctrl+Shift+P</kbd> → I print `Exalt`, but I not see Exalt commands in command palette. I press <kbd>Ctrl+Alt+X</kbd> and <kbd>Ctrl+Alt+V</kbd> hotkeys, but nothing occurs in my incorrect XML files.

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by eerohele** [comment]
I suspect this issue might be related to 32-bit Windows.

Exalt depends on [lxml](http://www.lxml.de), which needs to be compiled separately for the 32-bit and 64-bit variants of every OS. Support for 32-bit Windows was [contributed by @debjan](https://github.com/eerohele/sublime-lxml/pull/2) -- I actually don't even have a 32-bit Windows installation I could test on. (I could also never get lxml to statically compile on Windows so that I could package it with Exalt...)

So, unfortunately, I'm not sure how much I can do to help you. One thing you could do is select View > Show Console in Sublime Text and see if the console reports any errors while trying to load Exalt.

**Comment by Kristinita** [comment]
@eerohele , the problem is not repoduced for me in Windows 10 64-bit EN LTSB. In Windows 10 32-bit [**I have problems with lxml intallation**](https://bugs.launchpad.net/lxml/+bug/1633987).

Please, write in the `README.MD`, that users needs install `lxml` dependency.

Thanks.
